[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.5.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.11"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/badoux/checkmail"
  version = "1.1.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"
